name: Server Release

on:
  push:
    tags: [v*.*.*]

jobs:
  publish:
    name: Publish server docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: docker_meta
        name: Docker meta
        uses: docker/metadata-action@v4
        with:
          images: agnjunio/albion-killbot
          tags: type=semver,pattern={{version}}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Server
        uses: docker/build-push-action@v3
        with:
          context: server/
          file: server/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  deploy:
    name: Deploy server
    runs-on: ubuntu-latest
    needs:
      - publish
    environment:
      name: production
      url: https://albion-killbot.com/
    steps:
      - name: Execute deploy script on production server
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker compose --ansi never pull
            docker compose --ansi never down
            touch migration-state.json
            docker compose --ansi never run --rm bot npm run db:migrate
            docker compose --ansi never up -d
